apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: orino
spec:
  encryptedData:
    rootUser: AgBJNNebLRk7zTE0DcGhIHMe8/oen9L4J4WvPDsUxyb9NbloW5JI6HmpV3VHFBUzAibHXkhy+YYRZStmgKhvo3hUVS5Z3z6A8Sbj1ZU8u3FYHC4gg5TlhoVpZD9fa1zkrJS2sKlt03z8p1QeQFDqH4e6WFqHInyzeseWSuLZXXSrJqNYtAnJ4Qk8/cccHjR6tvYTTfbQU3MqRLcp7phWbZrJG+jtJDqrnGNgdPbQanisSFmjTS+iQmlm2m9YqkCDTwTO8DhBIFWGyvzMykeJ9hukDD+ge4H04deXAQuALbAOfTbv4VbYE995pz7IdwRkJmZpvX0aKy5Fp6NxWTiwdWanZSoK6AZ9H8KGq1jLGgby89Aaj3wLjjjYR5x3K+zwmmI7bZyk69amvNdjnrcag8FLy9x+vQkji/63aZLYxAMzV9Gv5OrZ61x28gvLjcQSZ3qq4AUR2HW9GM3tK9PXa2P1xFQka3JSe3GmreBkpuQdRGgVLq4INrBu47KGC1y6wqPss5GYF6ZHo/tico+iM/6hoHH/PYE5MmAp6t+1B4USNlPipawjuVMmFsksCW8MHZBRschUWMtuE4Wr+Vy+d8J3sNVLXa1kZlFiVeo+HgPVyZCvP9jaHP7lzEimzg/p1T8kI5byzZb/RrTNQBMc+i82bm2ZH4NhBySE9Nuq1ECbCgMP6mRb8CmuZ6fcM6GNAw/7hZI6uYg5f+no
    rootPassword: AgCakgviu13Pq+HJN/O+n3qNvBRN9jBt5bx364f08ykhbo8Fuavk8KyHGNpvtNUvMkWtRkAlVi1jS7b9y9Oo8TLNXP+exkGOjmS0xYCdE6bWiuyV0+gJ3IQMD/NC1leEfFLfQIg7TagbuEDihtpIUdo3fg/f+1jSXcqRRUwWoH4f8GuGIuAHhNzx+FtQoZhI+ISczlzJzvWjR/0w+lH/98XCHdCo3HYgSd1fS3DNUoV3Bx1GeRPZsNSe7kmhM3g0DoaGC75eJCbpF/9Cu7BKB3XPE9ubUZ2HXkAzdjbcAwQcHk+I6CsYktcpex86khbFbfP3+fgYdjmynH3VEkOzHN8nrWxX5xiILexgxVkUpd/42+7jz5GwlkgUs32o9fsd7mI8gwxL3hu9Di464pWWlEIDMF3wRZHeG0Q2j47g9FNKpTPmUSQncD/m0p2KpFiRHxjts11kJ+MmgR4Mn/MA7Bv+bx1tS1BatOp1cKLTgC/KVJnCvWWK4hNHf2zplWX+qK6NHsApNJHRZeQeAR2FFlzHDxY7J1kzzPodFQ0TAmdHB6td251r7t51a7RUZ5krvaKHQTWsRmYJBXLEzalsNklXxsIDJ/SWTZCoxtn9yx8hSFDyf7Ry82L8/0P8qKDG88BwCi9S1crMJh93Amwqm+HEjzpdFnx248i27EgFQEje4uCH2VKOKZuHt59s/xK+J8qBjxU+N6PpSP4C
  template:
    metadata:
      name: minio-secret
      namespace: orino
    type: Opaque
