apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: orino
spec:
  encryptedData:
    rootUser: AgCjDjOHYI6YBnirH1ugNq0PXTBJXVcaT7/uPVdI44sazgEsQ578YDrlwFMm83WcEfKBr3V8B0uZzRiwPTmgJwqhQ0L9Tr74wcLmOlaKgNs7O8rnK4u3yQKpjLN2YtztSOojb0iSPzenp0ZljjlnPFl+/ijCcNcOp8LKwsZnW2VBDrvoNOwCypq/q2hzwFVcJwM5wTrthEuZoBfULwJ/3iwFldhix1TFf1B4XurDXdIZHigGYWuFgUme0bNTCPhjvhWauOTyTdyJNRomNqAVyJf81Zy5/kZq2y6oYthUTpDtnuFk7uvpdxiccpNlukCgx1VdjImWy0oikaRsh/Nd68ZseOJzkjkLUsjn1vRuiOrubTTKp/SggFtguIYR8aggrtPOXgmxprECVHfGAjv3Qz+R/ctSunh4maLv8KoC1aDobBQ9qgEsi2z+1EZ98UrVR/FeNeYTTj4n7Ivvo9uAYofD4VQF8vj3i5MHpul9KFcP+vWbm4OomGt+S3XqnYYKAybKtZCeviL8LXP1RrAPVPPiqmTuDEQ9BdUTQVDg07Nt4sMt0IoEbL+wifh8G6JdMihbRkAP7OEraIz/CDcJpE3eyR0p6c0u3BR84zq0J4n8AvmCB9zpzv+sl/Kb1uFdQ0DtqBYhTtxlQ53M6qPA+Ic7XyKO9caqD3XUnPT9IVYoI8Hxd8zhU8F5f/0Mj8qCE2SGlIjhtn+PIvbRj7N7JgU=
    rootPassword: AgBnyw9Mn3WXX7DzDlyTIPANDTlfReVxUc3i3xfRdrH0SWdmU4rwGWvYTS8ju4zjX95BbY/g4nhf37rAPT3o8Sjv95AewLdJ8fx1VMOIL3IfVPsLLqDd0D6ljr57ZZ1hAtAz86/ddAUD+ZvWRMcMGOzLzJ4bSDm7ENLaXMOBXtNoR5AI75pdqP5dexqcQz+ywMEnO7oZF9kxqX7i9yLcfwasXTso7jTw5C4tu9jeldAsekBVdlWogX1uIMDnRrS5uf21phqz6MSJU389YASXvLHa5S7GAoOHNVbzpL4RTFCInaZYkpwUc9j8TQziVuJU9LpJOSsLCU40179SYdL9eC6xLpqkr+PmMF/hPGbOzwVpyYBvSxiXKQb7KflVSC+WSoClnZx1oXrLo/YT6I7ape80aVRHG905EAs0v5MZRd87gUjqfDX/I4Gje9/8DSScEoupkOH1BTNzXwpPoNYyuPCgeWK6RBUq+I2wU4cwcakpacqgt8kwmLqYSg5EAzam+sBbhhMXOB2Muknr1wxwgLkF7WqIZhTVjfrQ42ZOUWbi/G2FEGwktXzYhaau4neU6FD8jSbbsVLVJ++R8KLfdb4nA2siAwENZjQkF1l9KXSVFnkd4bANYafDbY/TyxaAJUS2nhJhWsvlsfAjUDqK4ZhhodhfKahB11xwCrmBPFgHSxMrc4Ab+1Y74rwn7bWoanRdQOO8kA13iX5Z5N6owrY8011w7lgBvzQ=
  template:
    metadata:
      name: minio-secret
      namespace: orino
    type: Opaque
