apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos
  labels:
    app.kubernetes.io/name: thanos
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
  endpoints:
    - port: http
