apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis
      component: metrics
  endpoints:
    - port: metrics
      interval: 30s
