apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: be
  namespace: istio-ingress
spec:
  hosts:
    - "api.orino.dev"
  gateways:
    - orino-gateway
  http:
    - corsPolicy:
        allowOrigins:
          - exact: "https://orino.dev"
          - exact: "http://orino.dev"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
        allowCredentials: true
        maxAge: "86400s"
      route:
        - destination:
            host: be.orino.svc.cluster.local
            port:
              number: 8080
