apiVersion: v2
name: cert-manager
description: cert-manager 인증서 자동 발급
type: application
version: 1.0.0
appVersion: "v1.20.1"

dependencies:
  - name: cert-manager
    version: v1.20.1
    repository: https://charts.jetstack.io

keywords:
  - cert-manager
  - tls
  - letsencrypt
