image:
  repository: ghcr.io/wcorn/orino/be
  tag: latest

replicas: 1

env:
  SPRING_PROFILES_ACTIVE: prod
  MYSQL_HOST: mysql.orino.svc.cluster.local
  MYSQL_USERNAME: orino_app
  REDIS_HOST: redis.orino.svc.cluster.local
  REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy.monitoring.svc.cluster.local:4318

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
