apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-secret
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgB7NFyd3SH9kXFCBbECK3xxnhSyRCi2blBEVFhYbLCzud5LxlXakxNCrKrY00Jw6o7riRqQa4Fr8L/wXY5b8lDlVOH6dn3/0rARpScz1pifjLJcDdx5z3+6q9f2HzNlo4bt1I0AvlwjAhiBn3cOkiq+m4UnKVgFmGjQNkiqL895YUk7DO982gwZHjss0I1zNV5R2iOGfbicJE6f9BLD8I43ilVTdQ6XETd1sc1J6zd/HKUiBo6Xo/MwNc+oegT+zzCaNIJoWU52s7sw8KdqzkeVHBv54Ap1rsohk/5BsEOLEAPC2Ff2IVOh2V6qWi6PlzJXl5L9U/jZIlMFCdsU0D6Z/pm3W5ulRXa5Ql7qCLjorvXMn7wxn94mAC78cnbalj+L6an+StjrztvNSHeHDLMiMCZHUExgTcXKFFWmKGEJvE6P0ovMpbuWtC58JreMeprro+7WZ7hTl/oJj+R0sfNLRJbkaMRz1nvPg8NanUx4xdiVKcy1fe8oPPZyETBvQvob+0EiAMrOgDGk5Gbfaag50qf/HaUH/uD5xt8ThtUtujLIjyPgZ5UWGu0NxuNVSldPatmLZc81NYTolTTX6RzaS/Aiw+6F6OABnAFqVFtZ733ol3eMhW4AZca9pcNXOzB9rHo74FE51NTr2VN7T4/ItFx5KR8VsfVKXqgSIrTDFcR3S1Ph1kcQ4WL84SXYOUBiSatgn9vVY1RdhV1tg159Kt/G3tMaNm3NgLkguUPf24cDLPb3ReLE48q5IV82rRkdovHyo84pOILMkR9cq8KVZ5UDK3i2MPpm6GCAfQD64SxWmtgH3sIIxTSojqFjdMZrGL07Xp/TsaGZpn63R3rXMVoTAc06sOZI
  template:
    metadata:
      name: alertmanager-discord-secret
      namespace: monitoring
    type: Opaque
