apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgAQ0HbIjOycye2iBbcC3l+n6381xAOb1O7FBwC9iNXCgGa57PFod9vU1pNyJtk7qXSE3JeMOAqnE7GBvzGDJP8yF4trhiwaGE/lBxNwvB+Hhjtjrxq05OTDuvFfogfk0zWggd7P9U+BLzvTtO952yjeWM6lwGuQWnHYmQpSG0CCB6xLqI/4Te4hMtCx46x5ABXx6AzSzhVx3/il+0diTjCqlyG7SEAWUMufCER6wUnKrtgQZd7aRiC/p8Ra1Ft7Ix7/RkYLQELQxenPMXlf3CJ2ddjjkBLGzEveZPZB09qBH5+QqQQG7vxoYqlvG8uOqM0SYrhamuAV/jirkA/N1ba21tsAnt4Tb1+iePJ3hJP6dHi8cANrYUYWsPYGG6nvhk0qD9r63LEtFo+R0a43B7a3Uqtx4mbbIcxTfH03MOjPlosz/+kXrt1vBSJ+oi6PHL6pNaowRncJ6GvAxg+SzoYXtjgkNRzMGoY5MWrVWziXRjQmj8FyjdXSKWRCWbN1CUqiGhH8kTsP0cbilSLTgvONtDM0n1VTxwxizI0IEcXd5JLeEuCQi+uz4y8n8AEbnNrAiEWsUDbHMOWmViEEpQZ/I+sT2Eqp+PIYfpq9QGr42BgLwUjTsvj9JCjHGb19LLlYaadj49yc0+K3oJTYSVPBPf3vCO6RCW+V6O49kUi4+SZTRHrSV+VpkgbkDdEtqEuXD8OTJZuBQVFCp3qJUJ+YbUBPhscZ6Vib6pQX8fS/5wm/n0tU6oOfEhkV3FDzg8OIbqCqxaOx94AM7t2M9ONNNTgaFzCFtGC9HOkvvuWvVior9NLNBpqg4buMbDsG9dtK7JltHuygLC1PUibWpOePDda+J7PdV5bMISAZzLFd+TwpXNAwaxZ9xTEv0aeC4OnBuFmTgQBVbdrTG6ueqM4IpxlXpoNN15gdF7zklSvrYTJOhCe9c/P9M0dAfkJkjWN+HqTmggE8D2j9Ptm3wg==
  template:
    metadata:
      name: thanos-objstore-secret
      namespace: monitoring
    type: Opaque
