apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-secret
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: alertmanager-discord-secret
      namespace: monitoring
    type: Opaque
