apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgBwtnL2/+SeZ3b+5ib+j5AIGUo6jKxmlQDhBHq8cIU2ZMZ4HA66NWaEEPne+3pkD/fe8Ugjv8bAjX0dwrx7D4/MdF5O8ERgceTKKPG7pIC+LCxaooL+PTQQbkfDZdCkBcHGeUDNoxnkENiNvyQuzckK527lAYggvj7WGrvgVCuc5/sATmE1izea+CbMjvmiKkpUyHayaLLqG70kf4POlOvtBFl7NeKaETppcuCIx+BwmE1eEQK6Vtij5o7zT8DddjXrI0wbriZ8FT9x6gL0KL6Q1Dsu69vp1ZTlYEhCIeBsE5cq+ARPC0qz/hNKubRyhvrNnJYggChjUHVxu9OSD4yu2tyXYQltybc91I0raQ14aNgOhbM4Xj6ToIZyRpOSsZ7tC4tiXbVWl/zXFOqB9HEY+CFGq/pBWw9ZRAn2BJ/8zRfbHb7rssAgdWj/C354reI1CW2LqCmSK1RWVVYEGYkzUQBKpicH0hefnuzqmrTq5zo15i7pmaTyN5edFJr8UVAmnkK/mV4nwykrzKBbEHpFdvrigMQOqKjlvv7QS9C5udv34SQALPsa5X3XHl1ITDSFDN68mqqbVdKU8gLIX9N8/wHLhqn3D7O+zca0xTNn9oUUUXJ/rFL91gRjPoJzaP0hJU1GJlnvi7F2zviuQmUddArFgOPHyd4qhS8e3X5NXuoLagDr1iV8Vgma1rNcmT9fbbf4mw==
    admin-password: AgCNttmj52J8BbMqOqM95V1+QaL3SO/JBdqxc2XtYldnb35jfWcw0veGvFJKwF828TNt0bxGL0VCPIcDLGyg/ZDjz9T+0ejW+pOmlvHXmQP7IRJfBgZEHJHiMH7LPUMtpmWafXDoG0ADFYO7tenk/L4oXyS5U6xxVPh916+wPdm9zThzFnTEgufIU8D8Es2YRCrcJwONHQNOrVUdEea8ks0JgvRW17rZBXt8Lwwpr+6Wm39BoiwVQ4WAcT+koVHc3v+W2Ma3Lbgj0F/9a1owhT0TBX97qbfWVT0HZ86TDB9sD2fZyUgBlod0wMEMw56JLxdjz7kT08tYnsxwqmt52erop9RLZGO9kvxO/AKli3KP0Z9IbxWHURi6WyKqYlO+Ju4TB3oXG8eXDPrTCCEoCLJakB9isEBRKAPszoCDCGvUJB15X69/RDy9vg1xeHc/OlSaAwxGM5CQbQLVBMaq5Srzk9CV9JOBHf+utdnDkgNLXK+DfIS5nd3uVSbqZzqVV3ROPKPOIhhlbKf87kS0iFSp1vNUka/eqjzk1yvYzodTzeL7qQsi1EssTtLTC6ANkKAag6pkToaBvAQp3ZliqF4sccnueFdOd+URo3ymui4CZdT7wezrtQ9aKvHojql3mSLsXVyvgb313R/Pfb4YBT4KkHFdZgdziq0s+jdn1E0q8A3v5GxJGS3X27F7qv7w9Kx7EZPZyf3mBQRYetL14Fs=
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
