spring:
  config:
    activate:
      on-profile: dev
    import: vault://
  cloud:
    vault:
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      scheme: http
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      kv:
        enabled: true
        backend: secret
        profiles:
---
spring:
  config:
    activate:
      on-profile: local
    import: vault://
  cloud:
    vault:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    vault:
      enabled: false