apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: orino
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "be"
      useAnnotations: true
    - namePattern: "fe"
      useAnnotations: true
