apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: orino
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "be"
      images:
        - alias: be
          imageName: "ghcr.io/wcorn/orino/be:latest"
          commonUpdateSettings:
            updateStrategy: digest
            allowTags: "regexp:^latest$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
    - namePattern: "fe"
      images:
        - alias: fe
          imageName: "ghcr.io/wcorn/orino/fe:latest"
          commonUpdateSettings:
            updateStrategy: digest
            allowTags: "regexp:^latest$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
