apiVersion: v2
name: promtail
description: Promtail 로그 수집 에이전트
type: application
version: 1.0.0
appVersion: "3.5.1"

dependencies:
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts

keywords:
  - promtail
  - logging
