apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: observability-s3-secret
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBFL0HhxxKShZIJswiH3SZ0vgWlwNjf2kF+vKJMCPT99bL3b7ruWPV1QqkaJRAUFetltubRynmy363YfunZCbPSZHVsYN23LsROwasqChLyPdlwGDJJTEUHjI0LkVkVHFhgCiqihUH4dV394ud8xjQxRlyhpcsHs6clxxy15qGOOyblWM0CvLIdB+PyI+DAc/nYycpHhfpcUo7cQWb7dqt/GFIDGax+bIBJrNKhD0+0oy/knwfp74z+khjWWD7Iw/TXj9Qi3H2tkrPjxTjmSAPc1L5G8mdwd/SbwbQxrh18u6x5S+YIB7fbtIzurE5gBTA6sRvudPcMCKlOAJBUFuvyIRWma0aLqOYU1IibFMomqd/npXjI0fNUUIMnPDy/TMPVltV14+Dv2gn2z4K/ohPDrIc3mySLhBHQcLSIpsHCz+KM7+gFvtuHE67CJiw1xGUW7wMfUcJE6k0hkbQUXol8f6Wml285oAL7JnTf4YQOKbBPFt9vcfL6YHi1qbtNhEKX59nxz/CrX0phbUuZ4s5LFqWsLeuu+bHr98dZIzOiK9IRYP0ORcerVY5EeNcJL7EjCPRRuxHRStpVk2d5i6THL9iw4V+XRU20KAzvxaoMzYk7Y2RX9pvDze5RUVGeTLKRnEwbjxUCey4BMsF0NzPytjfWmti1FKSWABHVmeb7q6xVKTraO0qLQinNqiI1mVDcsXB2w4izwT/sEV9udhukuGm4Rg==
    AWS_SECRET_ACCESS_KEY: AgBjQyM9lym7q2rwUlXY7U6IvfFeqe2IepfU1nCOs4vGlYNOyX8j9Z2OQQ/Vmw6OWIXYCclJ8Zb/jSKymzAKuxWcASk2I+YCMvKTPLDSu3et2BjzFm+hLIxsckhrUe2PVS9FdOfN9BWvHjSyeK2M/LQds4vWChMfsM4jWD/6dEI2oeLxLSRy5CKerVIi07aZdW7vPcyVkfmlcrCHe4mGNz4iUgFrYsTpjBQOZ+0Tzjg9lkzCF2d11yWEYjqWphnHlJjVT4S46zJEc1kp0+kdNTSn0NrZOcPZ8CH0a7/CSOesJnsv/uSQfSZ+C5uuLvyeAoBoJLSoJTIJx+gczpCDJE8LKdFrUbMpQJhLYrpHCzkyRhdKD6p725wLhEprcxzvdpKHCuR7pS8MIrVc6P03nSZkAn7X3hdSC3n2uE9fedzWXKpzR87DbPInqXbiJ3w06hQ8TAtmHFjiuyYDFVmoYbBbPt1tatv+otM5yavOGNc5/JvB166Lr53SAY+oM2/pao4pPv2Zr0j4FCabR/1py5MD23L+e+xGld9U8JTb1UI6QHWBIm8uAKlEihsmklvgF5m87znUKC1Kl83h0R/ovm97TeWqUFZYFFWQSCyiSgm2vtGckgD85teqwCJm+JNMF82Lu812jmX2KgSdq6gRc6/HD/BlpSmZXy5lxk2PgaK2EerXwHQd+5INR7FxhuIvz2t2KiUyDQM4sP12XoeTRN3Li6Fr/5Hc10bmkFLNKXI6g3wtXPENXW8L
  template:
    metadata:
      name: observability-s3-secret
      namespace: monitoring
    type: Opaque
