longhorn:
  defaultSettings:
    defaultDataPath: /data
    defaultReplicaCount: 2
    storageReservedPercentageForDefaultDisk: 5
    guaranteedInstanceManagerCPU: 2
    backupTarget: ""
    backupTargetCredentialSecret: ""

  persistence:
    defaultClassReplicaCount: 2

  longhornUI:
    replicas: 1

  recurringJobSelector:
    - name: daily-backup
      isGroup: false
