apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-exporter-secret
  namespace: orino
spec:
  encryptedData:
    password: AgBft1ya/v1gTsdW1JAG+8Z7FFCgXhYLwEvZsifTVzcjJXXr/gAXbY7SLUbQGbfGtbulK+WUA74SO80OxOmhmychJGHH9cH0jEgZybjKrPesGslHYR7TawoEJR9XSjln7EMvQVBf+PPQwO8pHK28UBIjsa6DyRFMcM2Rr+3IkWXCyVxa1+2sG2agThRDfVcdayh7g4FHPh+aEoRqpJjulxfe/BeUPG95/Hj/e0Wblo7BekBinwzQJR78gYznKR6AESyQwVCz2FrZmIvRrxe4BaZGSrpo27JnJeEvh6EYiwAA/I29pOe3Whw++WOZAH38XDC1lHLNkh+N8TCTcaR32mpqwjzROVMGM16Wni5X7ZiplWwLYHdqaMQYq97torpR4Hi3YtgKZr294CWH4oLJ/ql/WL1rGoB3Jdcl6l5VrgJr/E+eIDn3d9NohcfNFEP9lygHyPSBmbsOER988O1OHUbiJotHM3Sr0IglrBdMl9QbHHwaF+DgbVvIrhL0lVt62kXIUD2+p6PjqQpjXZKMAEKCRBNpeWNr7me29CJVh2LlNfdj6Yeeh06CwUjpOq+F50Zjt9KZz7na+vAigh9BQBdLUAPxgvhDKSRM/cpBA9jIa1Jq5brjpIY2Ib6Bn734i8I3tbd6pbEYU5FkG6W6ZCsRKXLbJ3Z799d+UlPrjrmc0iC9AZA7aDqezGp9jgo3/uPtWUK11XT3SxCTBSQuI1ubxTgWEg==
  template:
    metadata:
      name: mysql-exporter-secret
      namespace: orino
    type: Opaque
