apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alloy-faro-secret
  namespace: monitoring
spec:
  encryptedData:
    FARO_API_KEY: AgCcZuH0NqK+1nOrZTjXfWYlnv6mntWj4y5qd/o/VICqVQANtoUjTTM6H6FpS2UDTL9y3I625aNm+tM6/wen4Hq6PTqGCdLUrk4YwFnQ6Jbu2/pJdC7nH1PnkjWMQ846eUrptKY+aSa0sHAla/AFPvo4uBiW0P/vHIXIrq9KOadBOZKe8MJYjYQfkxsPk5Snl/2NU6cKodmDerqfhbxlVRH1E5RNgVz/9U3EtqYiqG6WUWYUonNti6h7JfS7ZsN3yhLfElG7XfRKlUSlP0FFZi3BwfH4VJYnBdGUjlXCAJQKm1q6ANalE7YD1SMR71rJCEqxbJ42lSKLemeg0hW+eH4I83PJZs8v+wDZ93roHGjZneCco0GeNpqf0CyAQwYIV0NE3nd3n6/BaTrqA+YC/SitY/tFVPOd/qWojOyqdjc5yoMbZLamd6waABWFwNAowV2N9N/LyAKR/oXAbj/kvW5YmT/H/1v+pR4ExDXPx/JUHW4KtpBFdTtxdKYRPvzIT55FSZDobrerQsDyNbYcSwq/bU9VlrzkMNyB4A8A5l9NPAoTdTaayLAX8h+oroGj6NVbHvN5J4X5jCJQL9tKPdxCbD6yyzSe6Rk19Nn4+iwB025jUDokP7j8UVZt9Kl0urc+hPLQABg4+7oAM9p/XoMAkaNU+eNMvwgJb5IaLLuG+jra9eBu+Ug3f6XUywLBCQJOltmXPsf+RIC+dJf7h+DleEZX44xYo4PhAYCFnMtJnM52COdZsSI0akfzZKp6fMSdqycYQG1useXpT03Y+H1w
  template:
    metadata:
      name: alloy-faro-secret
      namespace: monitoring
