apiVersion: v2
name: metrics-server
description: Kubernetes Metrics Server
type: application
version: 1.0.0
appVersion: "0.7.2"

dependencies:
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server/

keywords:
  - metrics-server
  - hpa
