apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgACFnIn8+kh29H6rZi1+cmnkoBDSNFOG6KyCbvtolMoDVmyj7XjeUtPH3s8+gzjF/bhHa9YJC5gd+DFG1ubn5PSnT6+qTkQNt5ZXZgqWPZ7h5VFH6YJo+dNjW9K/WVjzB60cnmRsN2vz/+RrR/l0rXNdEc1SvIK+8ooB4ZLMT4lQR63NeeVUc908sXFpwBJzTDuw5eZpJm0ZBO7NKpnttKFbPNxOfdj88C2q90JLdPPPYpJMSx+gkLR/X7TsPIv64I0hpkOiCeEyckANnKGm4I6FqzDrZmrFBj2Ma/QddCCHEWjqTAspV3VRBKLI99z96mg1nusi+R5ARzyCD0BrywmILqOwyDdWsRNkNOySxXmBc4xVSIdaE750OZu74XWGmQswwrKKynGEUbr2yRoZUbegSPdJlUGgguYbEBGIbLLiToJO1AgvZBQUy9i/MIx5ZTR9ah7F7IqPRvLmmQgmATVyYpCp/wpu7H9bFsoLb6jzo9UuIXxKUQxG42O7lcBMcTyHY4oTyYE2m9J7lT+axgsljaE5NAaeNSg4j90bXfo5ku92jjq6ObfMFqj9QgO46esdfbFweO6gMQueunoqeCpNiJq+ByweIH0RGPzmoOUDnWA8eM9XGoCh6Y0yUA8DxwwXFN0o0GRTpjjv+2aifsC4rkERhYLG6tE1NLa2upgDqiAoEUmJil9qw2B807oluosiykz5irFckYtFyMIs8RavbdJepSLPHND49k43aXoY51QYc0UpIjrKeAaRUHnrsyNlUBuUJ0r+lb5Y+hOAUDyuv5bXJuxzjSU21JL/QaPGq1q/VfwlZJy9OSxPALsakXbQWXC9p0IPJ4HWGCT6ZuhWrbGK8VHTMfI
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
