apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cloudflare-tunnel-remote
  namespace: cloudflared
spec:
  encryptedData:
    tunnelToken: AgBp2zolpJ1QYe+b2UBj+VjHWqpk8TQDzy8sAI9R5T5hnGjHirNm1lA2mKYVDhP2j2nHac1xj9om1ypF7gBtnZlk/WUIyvJtMIGwofGabUt57+wGxDtXhx5PXaXTw+lnQXQFqzb5Dl0zk/PMbobfJUfgmfCnPPOtMsJhFyQlrkxtx1ZWN7s3lH2kXuc7hCaeYT2AqnBx4d6TVEaJZOzKSTuFQHSpJIlkof717252KdDR57umdNtsFjIRi+xw1cghJdiozAdtHPOkfB96nPLvQj0RE+wWKUEpLFhUOS6+9lhD+SQ6Cj1ILn3eguGi0HlpCc+m+0t+WJ/gKRk2ErKyFpbVKzyngcig1fynijVgZMJRUNKYC0IGAJN/Bn75VkHp8No32sRYAL9ovL9oF23RSH6xkAMMLihX2VGFgEHV3MUAM+8aC3VIjdPoH9QI5q3LqO5ak9r4Mz8lBktodLvyus4nfGpuN4BrE5aTDSqZFAz4uihhbuxuTPxpBzPnrc6C27pI1A/+7BwH4ha0o7OhLVk4ZeSxni1SMFluITvuXITAMC96tGOBofsN9WxgFksmx0DkFQuyqlQf9w5C8ES3lhhSYgtnjZZ1ECwa+0TqXfd0F2+8Cyq2Wmpu3irTVExpuF8gU1a20mDuGM8DHSlOQKhxIMEivo5y46TQQrfVGdikl9bYYdF2V2R0L1UkO0L6jOm5pzV8AFkkE6VlrpNPNLYPOiXoO5N3Qil6Az7VQWAcyvghh6vRyUodDHGTFY67MY+7wcHq1jUgQEtqvxnMHYQn8YyyiirJbljXqsqDBeIO7s+JG0KGaKKg1f1COQ2wzrOX2BAYYezcDMQ4J0I19fx+EYjQqMT6MoNDoeVQnc0JnuWWXiVoZqLSxWmbBXEksYLlNNWb1bpdfTT64rBwixHro6oRsihH8NGTeRxVH5FtcTVIQ5yU9Aen
  template:
    metadata:
      name: cloudflared-cloudflare-tunnel-remote
      namespace: cloudflared
