apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cloudflare-tunnel-remote
  namespace: cloudflared
spec:
  encryptedData:
    tunnelToken: AgBHnT91GRy3gZ3RtrsqvTCaVqHCzQZWKMhDAQ5v0TCthBQwhXI2vh3WYJtZaLZAeRn0qCqwiumTeiCmdbf9ich+rz82CydSseOy/CFRoq8a0me+j8qJ0inydpxjaa6fbqpmkkt5Res5m+viezLUXwijecEvQhSxRvOvyr/nH95d+qcEdovTLb/hXE9saxZwooKszSs53iw8qbmxwZYdeCa5kY2aJSBwZd32hQnvYt04b/cqaoDwW3VrkrYyw+uETaNKWK56vMiYgMHLgWw/ZZNK52WljCv2JclRMii0UuGVjZyxYgI7jqIAVWVlFDCqwRGyPDtz0yKuFxxzsm8dM5AW1fKj9ofIgnPdQYC8dya6f4o3fxxRZrFui3+/jUht5LfEpQ2XXXLy6O2h9wB06DeKavrueaDNp8MBSjPZaoZ6uoEbddPSaRFd3rpWDWEUwA9aBLjP5GUVHN2qqyDtoEFr3Ggv0xgYhffl4DfvVnm/tU7BwbORvQzoUL+x1LNxKXiIUYREGL6jMOev9Q+BBKBPimHeMupAXrGnUlIApD2LxfjGetnyZ8GQw4VgwZWFJa0dTFqGuoEDtBTmIIo7jKg5mQumLlu92mgDgBlqtIr1kSIRCkYBHsZwN8bZCakOnimOQc2d92khpOOYcWJhkb1aH0ccjNtnuOsqlHdU1uT+ip31ZoGY+R5Y3jPxAlHGBQYZfpHknceDvB0RBb+gEHrnL3KECeVzEFUxF1jGMam4pKWbEnGdDF95lQV16NoME6ArbOm7lkPs6Iy9Mw3mxGJ4d65ffwO4EcOT4zg1ekc8YRhQgKLB15aU0421Rx+N2cqB87n52HOEjk3tPMaV7kbwW8MtX+QlQvMUZJS4bT6XYTcWp44s+SOoXxeYt/Ps2WAl7yQo7cJAhz2UkhSWjdijY++XF8FdtyX752jj+ozfVW1XwAarFuiE
  template:
    metadata:
      name: cloudflared-cloudflare-tunnel-remote
      namespace: cloudflared
