istiod:
  meshConfig:
    enablePrometheusMerge: true
    defaultConfig:
      tracing:
        sampling: 100
    extensionProviders:
      - name: tempo
        opentelemetry:
          service: tempo.monitoring.svc.cluster.local
          port: 4317

  pilot:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 4096Mi
