spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${DB_NAME}?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${DB_NAME}?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.4.4:///toy
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
