apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: orino

  source:
    repoURL: https://github.com/wcorn/orino.git
    targetRevision: main
    path: infra/helm/cloudflared

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: cloudflared-cloudflare-tunnel-remote
      jsonPointers:
        - /data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
