apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: orino

  source:
    repoURL: https://github.com/wcorn/orino.git
    targetRevision: main
    path: infra/helm/ddns

  destination:
    server: https://kubernetes.default.svc
    namespace: ddns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
