apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.discord: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: orino

  source:
    repoURL: https://github.com/wcorn/orino.git
    targetRevision: main
    path: infra/helm/loki

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
