loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      type: s3
      bucketNames:
        chunks: orino-loki-logs
        ruler: orino-loki-logs
      s3:
        endpoint: s3.ap-northeast-2.amazonaws.com
        region: ap-northeast-2
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        s3ForcePathStyle: false
    limits_config:
      retention_period: 2160h

  singleBinary:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnv:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: observability-s3-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: observability-s3-secret
            key: AWS_SECRET_ACCESS_KEY
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

  chunksCache:
    enabled: false
  resultsCache:
    enabled: false

  gateway:
    enabled: false

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
