spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${DB_NAME}?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${DB_NAME}?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.4.4:///toy
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  tracing:
    enabled: false
