management:
  server:
    port: 9091
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        ready:
          include: readinessState, db
        live:
          include: livenessState
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
