image:
  registry: quay.io
  repository: thanos/thanos
  tag: v0.41.0

objstoreSecret: thanos-objstore-secret

query:
  replicas: 1
  stores:
    - dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.monitoring.svc.cluster.local
    - dnssrv+_grpc._tcp.thanos-storegateway.monitoring.svc.cluster.local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

storegateway:
  replicas: 1
  storageClass: longhorn
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

compactor:
  retentionRaw: 30d
  retention5m: 90d
  retention1h: 365d
  storageClass: longhorn
  storageSize: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
